#!/bin/bash 

# Define expected username and email
EXPECTED_USERNAME="TontineSaaS"
EXPECTED_EMAIL="developer@tontinesaas.com"

# Function to check username and email
check_username_and_email() {
    local current_username=$(git config user.name)
    local current_email=$(git config user.email)
echo '🏗️ 👷 Checking git configurations... 👷‍♂️🏗️'

    if [ "$current_username" != "$EXPECTED_USERNAME" ]; then
        echo "❌❌❌ ERROR: Username mismatch. Expected: $EXPECTED_USERNAME, Actual: $current_username ❌❌❌"
                echo '⚡️⚡️⚡️ PLEASE CHECK YOUR GIT CONFIG ⚡️⚡️⚡️'
        exit 1
    fi

    if [ "$current_email" != "$EXPECTED_EMAIL" ]; then
        echo "❌❌❌ ERROR: Email mismatch. Expected: $EXPECTED_EMAIL, Actual: $current_email ❌❌❌"
                echo '⚡️⚡️⚡️ PLEASE CHECK YOUR GIT CONFIG ⚡️⚡️⚡️'
        exit 1
    fi
}

# Check username and email
check_username_and_email

echo '🏗️ 👷 Styling your project before committing 👷‍♂️🏗️'
echo 'Please be patient, this may take a while...'
pnpm lint-staged 

if [ $? -ne 0 ]; then
    echo '❌❌❌ Styling failed. Aborting commit.❌❌❌'
    echo '⚡️⚡️⚡️ PLEASE CHECK ⚡️⚡️⚡️'
    exit 1
fi

echo '✨🎉✨ No error found: Git Config looks Good, Committing your changes... ✨🚀🏄‍♂️🍻'

exit 0